#! /opt/perl5/bin/perl -w

use lib './blib/lib', './blib/arch';
use Lingua::Ident;

$ident = new Lingua::Ident('data/data.de', 'data/data.en', 'data/data.it',
			   'data/data.fr', 'data/data.ko', 'data/data.zh');
$sample = "";

READ: while(<>)
{
   chomp;

   if(length($sample) < 128)
   {
      $sample .= $_ . ' ';
      $sample =~ s/\s+/ /og;
   }
   else
   {
      $lang = $ident->identify($sample);
      last READ;
   }
}

$lang = $ident->identify($sample);
print "Language: $lang\n";
